export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES_MAP: 'SET_CATEGORIES_MAP',
    SET_CATEGORIES: 'category/SET_CATEGORIES',
    // will be triggered when async request is made
    FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED'
}