// declaing the cart action types
export const CART_ACTION_TYPES = {
    SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
    SET_CART_ADD_ITEMS: 'cart/SET_CART_ADD_ITEMS',
    SET_CART_REMOVE_ITEMS: 'cart/SET_CART_REMOVE_ITEMS',
    SET_CART_CLEAR_ITEMS: 'cart/SET_CART_ITEMS',
    // SET_CART_COUNT: 'cart/SET_CART_COUNT',
    // SET_CART_TOTAL: 'cart/SET_CART_TOTAL'
}
